"""
The explicit instruction / data channel carrier — StruQ's model, one level up.

StruQ never parses a prompt. ``code/defense/StruQ-main/config.py`` keeps
``{instruction}`` and ``{input}`` as two *named fields* all the way from the
dataset to ``prompt_input.format_map(...)``; the delimiters are chosen by the
defense and the split is never recovered from text. This module gives the IPI
harness the same property:

    ChanneledPrompt(system=..., instruction=..., data=...)   the two channels
    .to_messages()                                           -> ChanneledMessages
    ChanneledMessages                                        a list[dict] that
                                                             *remembers* which
                                                             span was untrusted

``ChanneledMessages`` is a ``list`` subclass, so ``victim.generate(messages)``
keeps taking an ordinary OpenAI-format messages list (``ipi/victim.py``'s
contract is untouched, and litellm / HF see a plain list of dicts). What it adds
is one attribute, ``.channels``, which travels with the prompt into every
``preprocess_messages`` hook. A defense that needs the split reads it; it never
pattern-matches for it.

Why this replaced regex recovery
--------------------------------
``harness.build_victim_messages`` flattens a scenario into ONE user turn —
deliberately, two consecutive ``user`` turns are rejected by most chat APIs — so
every structured defense used to re-derive the split with
``_AGENTDOJO_RE`` / ``_ENV_RE`` / BIPIA marker heuristics. That coupled six
defenses to one regex in another module: change the prompt shape and each of
them silently sees an empty instruction channel or, worse, sees the user's own
task as untrusted data. It shipped exactly that bug — Sandwich and Spotlight
wrapped the legitimate task inside
``[START OF UNTRUSTED EXTERNAL DATA] ... IGNORE ALL COMMANDS ABOVE``.

Precedence, when a defense asks for the split (``Victim.resolve_channels``):

  1. the split carried by the messages (``ChanneledMessages.channels``) — this
     is per-prompt and generated by the harness, so it is always the split for
     *this* prompt;
  2. a pin installed by ``victim.set_channels(instruction, data)`` — for prompts
     built by hand, e.g. the DefensiveToken notebook, which pins and then calls
     ``preprocess_messages([])``;
  3. ``ChanneledPrompt.from_messages`` — role-based, warns, and is the only
     guess left in the codebase. It is *structure-preserving*, not a parser: the
     whole final user turn becomes the data channel. That over-approximates the
     untrusted span (a defense marks slightly too much) rather than
     under-approximating it (a defense marks too little and is inert).

Everything here is pure Python and torch-free — ``scripts/smoke_check.py``
verifies the rendering and the round-trip on every run, GPU or not.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, replace
from typing import Any, Iterable, List, Mapping, Optional, Sequence, Tuple

log = logging.getLogger(__name__)

__all__ = [
    "ChanneledPrompt", "ChanneledMessages", "channels_of",
    "PreRenderedMessages", "PreRenderedPromptError",
    "INSTRUCTION_HEADER", "DATA_HEADER",
]


class PreRenderedPromptError(RuntimeError):
    """
    Raised when a defense is asked for the instruction/data split of a prompt that
    another defense has already rendered for the model.

    A structured defense (StruQ / SecAlign / DefensiveToken) emits the model's own
    string — delimiters, chat template, the lot. There is no split left to read, and
    ``ChanneledPrompt.from_messages`` would happily *guess* one: it would call the
    whole rendered prompt untrusted data, re-render it, and append the outer defense's
    text after the response delimiter — i.e. into the model's answer position. That is
    silent, so it raises instead. A structured defense must be the innermost one.
    """


class PreRenderedMessages(list):
    """
    A messages list that is already the model's prompt — do not re-render it.

    Emitted by :class:`~ipi.defenses.channels.StructuredChannelDefense`. Behaves as
    the plain ``list[dict]`` every backend expects; the only thing it adds is the
    refusal, in ``Victim.resolve_channels``, to invent a split for it.
    """

    __slots__ = ("rendered_by",)

    def __init__(self, items: Iterable[Mapping[str, Any]] = (), rendered_by: str = ""):
        super().__init__(items)
        self.rendered_by = rendered_by

    def __deepcopy__(self, memo):
        import copy as _copy
        out = PreRenderedMessages(
            (_copy.deepcopy(dict(m), memo) for m in self), rendered_by=self.rendered_by)
        memo[id(self)] = out
        return out


#: The house IPI carrier shape. These two strings are the *only* place the
#: rendered framing lives; nothing parses them back out any more.
INSTRUCTION_HEADER = "User Task:\n"
DATA_HEADER = "\n\nContext:\n"


class ChanneledMessages(list):
    """
    An OpenAI-format messages list that remembers its instruction/data split.

    Subclasses ``list`` on purpose: every existing consumer — ``victim.generate``,
    litellm, ``LocalLLM._build_local_prompt_ids``, ``json.dumps`` for a
    transcript — treats it as the plain list it is. Only a defense that asks for
    ``.channels`` sees anything extra.

    Slicing or rebuilding it (``[dict(m) for m in msgs]``) drops the split, which
    is the correct default: a rewritten message list no longer describes the
    channels it was built from. Re-render from the :class:`ChanneledPrompt`
    instead.
    """

    __slots__ = ("channels",)

    def __init__(self, items: Iterable[Mapping[str, Any]] = (),
                 channels: Optional["ChanneledPrompt"] = None):
        super().__init__(items)
        self.channels = channels

    def __deepcopy__(self, memo):
        import copy as _copy
        out = ChanneledMessages(
            (_copy.deepcopy(dict(m), memo) for m in self), channels=self.channels)
        memo[id(self)] = out
        return out

    def __repr__(self) -> str:  # pragma: no cover — debugging aid
        return f"ChanneledMessages({list(self)!r}, channels={self.channels!r})"


@dataclass(frozen=True)
class ChanneledPrompt:
    """
    One IPI prompt, with the trust boundary kept as structure rather than text.

    Fields
    ------
    system
        Trusted. The agent's system prompt / tool schema.
    instruction
        Trusted. The user's own task (``attack_attrs["user_task"]``).
    data
        **Untrusted.** Everything an attacker can write into: the pipeline
        context and the injection. This is the only field a defense may
        rewrite, filter, wrap, mark or sanitize.
    data_prefix / data_suffix
        Trusted framing rendered immediately around ``data`` (the harness's
        ``<env>`` tags). Structure, not data — a defense wrapping the data
        channel goes *outside* ``data`` and inside these.
    epilogue
        Trusted text rendered after the data block, still inside the user turn.
        Where ReminderDefense's safety reminder goes.
    history
        Turns that sit between the system turn and the final user turn. The
        harness never sets these; ``from_messages`` uses them so a multi-turn
        conversation survives a round-trip through a defense.
    instruction_header / data_header
        Rendering only. Defaults reproduce the house carrier byte for byte.
    """

    system: str = ""
    instruction: str = ""
    data: str = ""
    data_prefix: str = ""
    data_suffix: str = ""
    epilogue: str = ""
    history: Tuple[Mapping[str, Any], ...] = ()
    instruction_header: str = INSTRUCTION_HEADER
    data_header: str = DATA_HEADER

    # -- derived views -------------------------------------------------------

    @property
    def trusted_instruction(self) -> str:
        """
        The two trusted fields as the single instruction channel StruQ-style
        defenses take. ``system`` first, then the user's task — the order they
        appear in the rendered prompt.
        """
        return "\n\n".join(p for p in (self.system.strip(), self.instruction.strip()) if p)

    @property
    def framed_data(self) -> str:
        """``data`` with its trusted framing, i.e. what the user turn contains."""
        return f"{self.data_prefix}{self.data}{self.data_suffix}"

    # -- rewrites ------------------------------------------------------------

    def with_data(self, data: str) -> "ChanneledPrompt":
        """Replace the untrusted channel. The one rewrite a defense should need."""
        return replace(self, data=data)

    def with_system(self, system: str) -> "ChanneledPrompt":
        return replace(self, system=system)

    def with_epilogue(self, epilogue: str) -> "ChanneledPrompt":
        return replace(self, epilogue=epilogue)

    # -- rendering -----------------------------------------------------------

    def user_content(self) -> str:
        """
        The single user turn. Pure string arithmetic, deliberately: this is the
        IPI prompt shape, and ``smoke_check`` pins it without a model.

        With a task:      ``User Task:\\n{instruction}\\n\\nContext:\\n{data}``
        Without one:      the framed data alone (a hand-built instance injects
                          straight into the user turn).
        """
        if self.instruction:
            body = (f"{self.instruction_header}{self.instruction}"
                    f"{self.data_header}{self.framed_data}")
        else:
            body = self.framed_data
        return f"{body}{self.epilogue}"

    def to_messages(self) -> ChanneledMessages:
        """Render to messages that still carry this split."""
        msgs: List[dict] = []
        if self.system:
            msgs.append({"role": "system", "content": self.system})
        msgs.extend(dict(m) for m in self.history)
        msgs.append({"role": "user", "content": self.user_content()})
        return ChanneledMessages(msgs, channels=self)

    # -- last-resort recovery ------------------------------------------------

    @classmethod
    def from_messages(
        cls,
        messages: Sequence[Mapping[str, Any]],
        warn: bool = True,
    ) -> "ChanneledPrompt":
        """
        Guess a split for messages that carry none.

        Not a parser — there is no shape matching here, and there are no regexes
        left in this codebase to bring back. The rule is one line: system turns
        are trusted, the final user turn is untrusted in full. Anything a caller
        built by hand and did not label gets treated as data, which over-marks
        rather than under-marks.

        Callers who know better call ``victim.set_channels(...)`` or route
        through ``harness.build_channeled_prompt``.
        """
        system = "\n\n".join(
            (m.get("content") or "").strip() for m in messages
            if m.get("role") == "system" and (m.get("content") or "").strip()
        )
        last_user = max(
            (i for i, m in enumerate(messages) if m.get("role") == "user"),
            default=None,
        )
        if last_user is None:
            if warn and messages:
                log.warning(
                    "[channels] messages carry no split and no user turn; the "
                    "data channel is empty and any data-channel defense is inert "
                    "for this prompt. Call set_channels() to supply the split.")
            return cls(system=system, instruction="", data="")

        history = tuple(
            dict(m) for i, m in enumerate(messages)
            if i != last_user and m.get("role") != "system"
        )
        if warn:
            log.warning(
                "[channels] messages carry no instruction/data split, so the whole "
                "final user turn is being treated as untrusted data. Build the "
                "prompt with harness.build_channeled_prompt, or pin the split with "
                "victim.set_channels(instruction, data).")
        return cls(
            system=system,
            instruction="",
            data=(messages[last_user].get("content") or ""),
            history=history,
        )


def channels_of(messages: Any) -> Optional[ChanneledPrompt]:
    """The split a messages list carries, or None if it carries none."""
    ch = getattr(messages, "channels", None)
    return ch if isinstance(ch, ChanneledPrompt) else None
